# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the 
# server process.


# Basic Site Settings
locale                   : "en-US"
title                    : "Dikra Bajgai"
title_separator          : "-"
name                     : &name "Dikra Prasad Bajgai"
description              : &description "Research Associate"
url                      : https://dikrabajgai.github.io
baseurl                  : ""
repository               : "dikrabajgai/dikrabajgai.github.io"

# Site Author
author:
  avatar           : "profile.png"
  name             : "Dikra Prasad Bajgai"
  pronouns         : "he/his"  
  bio              : "Short biography for the left-hand sidebar"
  location         : "Kathmandu, Nepal"
  employer         : "ICIMOD"
  email            : "dikrapb@gmail.com" 
  googlescholar    : "https://scholar.google.com/citations?user=iGSD8e8AAAAJ&hl=en"
  orcid            : "https://orcid.org/my-orcid?orcid=0000-0002-4491-3050"
  linkedin         : "https://www.linkedin.com/in/dikra-prasad-bajgai-4b5663176/"
  github           : "academicpages"

# Categories
publication_category:
  publications:
    title: 'Publications'

# Site Settings
breadcrumbs              : false
future                   : true
read_more                : "disabled"

# Collections
collections:
  publications:
    output: true
    permalink: /:collection/:path/
  blogpost:
    output: true
    permalink: /:collection/:path/
  cv:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # Publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # Blogpost
  - scope:
      path: ""
      type: blogpost
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # CV
  - scope:
      path: ""
      type: cv
    values:
      layout: single
      author_profile: true

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Conversion
markdown: kramdown
highlighter: rouge

# Outputting
permalink: /:categories/:title/
timezone: Etc/UTC
